type MockElement = {
  id: string;
  type: 'button' | 'link' | 'area';
  text: string;
  selector: string;
  position: string;
  style: Record<string, string>;
  pageUrl: string;
  siteUrl: string;
  frameUrl: string;
  frameSelectors: string[];
  floating: boolean;
  createdAt: number;
  updatedAt: number;
  beforeSelector?: string;
  afterSelector?: string;
  actionFlowId?: string;
  actionFlowLocked?: boolean;
  actionFlow?: string;
  containerId?: string;
  scope?: 'page' | 'site' | 'global';
  stylePreset?: string;
  customCss?: string;
  layout?: 'row' | 'column';
  href?: string;
  linkTarget?: 'new-tab' | 'same-tab';
};

type MockFlow = {
  id: string;
  name: string;
  description?: string;
  site: string;
  steps: number;
  updatedAt: string;
};

type MockHiddenRule = {
  id: string;
  name: string;
  note?: string;
  scope: string;
  site: string;
  selector: string;
  updatedAt: string;
  enabled?: boolean;
};

export const mockElements: MockElement[] = [
  {
    id: '56bb644c-ac15-42cf-a3f6-9b7b7b76f7a4',
    type: 'link',
    text: 'Dashboard',
    href: '/sitesettings/stats',
    linkTarget: 'same-tab',
    selector: 'div#__layout > div > div > header > div',
    position: 'append',
    style: {
      color: '#2563eb',
      fontSize: '11px',
    },
    pageUrl: 'https://note.com',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/',
    frameSelectors: [],
    floating: false,
    createdAt: 1763452627914,
    updatedAt: 1763858504570,
  },
  {
    id: '358dabbd-23f0-437e-be55-9e6d57262199',
    type: 'area',
    text: 'Highlight area',
    selector: 'body',
    position: 'append',
    layout: 'row',
    style: {
      backgroundColor: '#f59e0b30',
      borderRadius: '14px',
      color: '#0f172a',
      height: '80px',
      left: '398px',
      position: 'absolute',
      top: '7px',
      width: '329px',
      zIndex: '2147482000',
    },
    pageUrl: 'https://note.com/sitesettings/stats',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/sitesettings/stats',
    frameSelectors: [],
    floating: true,
    createdAt: 1765326879172,
    updatedAt: 1765326919396,
  },
  {
    id: '9a3dd7c1-d5a4-4003-a259-ffa12e1b6de6',
    type: 'button',
    text: 'Publish',
    selector: 'body',
    actionFlowId: 'flow-publish',
    actionFlowLocked: false,
    containerId: '358dabbd-23f0-437e-be55-9e6d57262199',
    position: 'append',
    style: {
      backgroundColor: '#1b84ff',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '12px',
      fontWeight: '600',
    },
    pageUrl: 'https://note.com/',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/sitesettings/stats',
    frameSelectors: [],
    floating: false,
    createdAt: 1765326888518,
    updatedAt: 1765326905920,
  },
  {
    id: 'b9c1f0c4-3e7d-4b2a-9b47-1a2d4b6f93a1',
    type: 'link',
    text: 'Help',
    href: 'https://note.com/help',
    linkTarget: 'new-tab',
    selector: 'header .help-link',
    position: 'append',
    style: {
      color: '#0f172a',
      textDecoration: 'underline',
      fontSize: '12px',
    },
    customCss: 'font-weight: 600;',
    pageUrl: 'https://note.com',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/',
    frameSelectors: [],
    floating: false,
    createdAt: 1765401200123,
    updatedAt: 1765402200456,
  },
  {
    id: '67a4f79e-91d8-4d2e-8ab1-6b2c7f3e2c8a',
    type: 'area',
    text: 'Sidebar block',
    selector: '#sidebar',
    position: 'append',
    layout: 'column',
    style: {
      backgroundColor: 'transparent',
      border: '1px dashed #94a3b8',
      padding: '12px',
      position: 'relative',
      width: '260px',
    },
    pageUrl: 'https://note.com/creator',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/creator',
    frameSelectors: [],
    floating: false,
    createdAt: 1765403200123,
    updatedAt: 1765404200456,
  },
  {
    id: '2f5d9f1a-5d2d-4f2a-9b3c-3b8f7d1c9e2f',
    type: 'button',
    text: 'New post',
    selector: '#sidebar .new-post',
    actionFlowId: 'flow-note-1',
    actionFlowLocked: true,
    containerId: '67a4f79e-91d8-4d2e-8ab1-6b2c7f3e2c8a',
    position: 'append',
    style: {
      backgroundColor: '#10b981',
      borderRadius: '999px',
      color: '#ffffff',
      fontSize: '12px',
      padding: '6px 12px',
    },
    pageUrl: 'https://note.com/creator',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/creator',
    frameSelectors: [],
    floating: false,
    createdAt: 1765405200123,
    updatedAt: 1765406200456,
  },
  {
    id: '5d1c4f7a-0b3d-4c2e-8f5a-7c2b1e9d4f3a',
    type: 'button',
    text: 'Subscribe',
    selector: '.subscription-cta',
    actionFlowId: 'flow-note-1',
    actionFlowLocked: false,
    position: 'append',
    style: {
      backgroundColor: '#2563eb',
      borderRadius: '999px',
      color: '#ffffff',
      fontSize: '12px',
      fontWeight: '600',
      padding: '6px 14px',
    },
    pageUrl: 'https://note.com/featured',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/featured',
    frameSelectors: [],
    floating: false,
    createdAt: 1765407200123,
    updatedAt: 1765408200456,
  },
  {
    id: 'c4a1f28b-9d7e-4d3b-8b22-5f6c7d8e9012',
    type: 'link',
    text: 'Pricing',
    href: '/plans',
    linkTarget: 'same-tab',
    selector: 'nav .pricing-link',
    position: 'append',
    style: {
      color: '#2563eb',
      fontSize: '12px',
    },
    pageUrl: 'https://note.com',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/',
    frameSelectors: [],
    floating: false,
    createdAt: 1765410200123,
    updatedAt: 1765411200456,
  },
  {
    id: '1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f809',
    type: 'area',
    text: 'Promo banner',
    selector: '.promo-banner',
    position: 'append',
    layout: 'row',
    style: {
      backgroundColor: '#0f172a',
      color: '#ffffff',
      padding: '10px 14px',
      borderRadius: '10px',
    },
    pageUrl: 'https://note.com/',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/',
    frameSelectors: [],
    floating: true,
    createdAt: 1765412200123,
    updatedAt: 1765413200456,
  },
  {
    id: '8f6e5d4c-3b2a-1908-7f6e-5d4c3b2a1908',
    type: 'button',
    text: 'Follow',
    selector: '.profile-header .follow',
    actionFlowId: 'flow-note-1',
    actionFlowLocked: false,
    position: 'append',
    style: {
      backgroundColor: '#f97316',
      borderRadius: '999px',
      color: '#ffffff',
      fontSize: '11px',
      padding: '5px 10px',
    },
    pageUrl: 'https://note.com/u/author',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/u/author',
    frameSelectors: [],
    floating: false,
    createdAt: 1765414200123,
    updatedAt: 1765415200456,
  },
  {
    id: '9e8d7c6b-5a4f-3e2d-1c0b-9a8b7c6d5e4f',
    type: 'button',
    text: 'Join now',
    selector: '.cta-join',
    actionFlowId: 'flow-note-1',
    actionFlowLocked: true,
    containerId: '1a2b3c4d-5e6f-7081-92a3-b4c5d6e7f809',
    position: 'append',
    style: {
      backgroundColor: '#22c55e',
      borderRadius: '8px',
      color: '#ffffff',
      fontSize: '12px',
      padding: '6px 12px',
    },
    pageUrl: 'https://note.com/',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/',
    frameSelectors: [],
    floating: false,
    createdAt: 1765416200123,
    updatedAt: 1765417200456,
  },
  {
    id: '0f9e8d7c-6b5a-4f3e-2d1c-0b9a8c7d6e5f',
    type: 'link',
    text: 'Community',
    href: '/community',
    linkTarget: 'same-tab',
    selector: 'footer .community-link',
    position: 'append',
    style: {
      color: '#0f172a',
      fontSize: '11px',
    },
    pageUrl: 'https://note.com/featured',
    siteUrl: 'https://note.com',
    frameUrl: 'https://note.com/featured',
    frameSelectors: [],
    floating: false,
    createdAt: 1765418200123,
    updatedAt: 1765419200456,
  },
];

export const mockFlows: MockFlow[] = [
  {
    id: '7b35d69b',
    name: 'test1',
    description: 'Login flow for the test page.',
    site: 'note.com',
    steps: 10,
    updatedAt: '2026-01-03 14:05:08',
  },
  {
    id: 'd183df69',
    name: 'test2',
    description: 'Form submit with validation.',
    site: 'note.com',
    steps: 6,
    updatedAt: '2026-01-03 18:22:41',
  },
  {
    id: 'e308ee5c',
    name: 'C23',
    description: 'Core flow for primary actions.',
    site: 'note.com',
    steps: 5,
    updatedAt: '2026-01-03 20:09:36',
  },
  {
    id: '466bc61a',
    name: 'template-short',
    description: 'Quick template run.',
    site: 'note.com',
    steps: 3,
    updatedAt: '2026-01-03 20:20:16',
  },
  {
    id: 'flow-gmail-1',
    name: 'gmail-cleanup',
    description: 'Archive and label a thread.',
    site: 'note.com',
    steps: 4,
    updatedAt: '2026-01-02 10:02:44',
  },
  {
    id: 'flow-note-1',
    name: 'note-stats',
    description: 'Open stats and export data.',
    site: 'note.com',
    steps: 6,
    updatedAt: '2026-01-02 12:10:31',
  },
  {
    id: 'flow-pay-1',
    name: 'payment-checkout',
    description: 'Fill billing form fields.',
    site: 'note.com',
    steps: 5,
    updatedAt: '2026-01-01 15:01:28',
  },
  {
    id: 'flow-note-2',
    name: 'note-publish',
    description: 'Publish a draft and share link.',
    site: 'note.com',
    steps: 4,
    updatedAt: '2026-01-03 09:12:22',
  },
  {
    id: 'flow-note-3',
    name: 'note-analytics',
    description: 'Open analytics and export CSV.',
    site: 'note.com',
    steps: 7,
    updatedAt: '2026-01-03 09:40:11',
  },
  {
    id: 'flow-note-4',
    name: 'note-scheduler',
    description: 'Schedule a post for tomorrow.',
    site: 'note.com',
    steps: 5,
    updatedAt: '2026-01-03 10:05:34',
  },
  {
    id: 'flow-mail-2',
    name: 'gmail-cleanup-archive',
    description: 'Archive read threads in Promotions.',
    site: 'note.com',
    steps: 6,
    updatedAt: '2026-01-02 11:15:09',
  },
  {
    id: 'flow-mail-3',
    name: 'gmail-labeling',
    description: 'Apply label to unread invoices.',
    site: 'note.com',
    steps: 3,
    updatedAt: '2026-01-02 11:42:55',
  },
  {
    id: 'flow-shop-1',
    name: 'checkout-address',
    description: 'Fill shipping address form.',
    site: 'note.com',
    steps: 5,
    updatedAt: '2026-01-01 18:30:44',
  },
  {
    id: 'flow-shop-2',
    name: 'cart-cleanup',
    description: 'Remove unavailable items.',
    site: 'note.com',
    steps: 4,
    updatedAt: '2026-01-01 18:45:10',
  },
  {
    id: 'flow-pay-2',
    name: 'payment-retry',
    description: 'Retry failed payments.',
    site: 'note.com',
    steps: 2,
    updatedAt: '2026-01-01 16:10:02',
  },
  {
    id: 'flow-pay-3',
    name: 'payment-update',
    description: 'Update billing details.',
    site: 'note.com',
    steps: 5,
    updatedAt: '2026-01-01 16:22:41',
  },
  {
    id: 'flow-news-1',
    name: 'news-digest',
    description: 'Open daily digest page.',
    site: 'note.com',
    steps: 3,
    updatedAt: '2026-01-02 08:12:33',
  },
];

export const mockHiddenRules: MockHiddenRule[] = [
  {
    id: 'e8611d35',
    name: 'Hidden rule',
    note: 'Auto-hide popup ads.',
    scope: 'page',
    site: '51cg1.com',
    selector: 'div.adspop',
    updatedAt: '2026-01-03 12:01:11',
    enabled: true,
  },
  {
    id: 'ca5d7ab9',
    name: 'Hidden rule',
    note: 'Hide sticky chat widget.',
    scope: 'page',
    site: 'missav.ai',
    selector: 'div.bottomRight--h0VsQ',
    updatedAt: '2026-01-03 12:05:42',
    enabled: true,
  },
  {
    id: '9157b809',
    name: 'Hidden rule',
    note: 'Suppress header ads.',
    scope: 'page',
    site: 'www.yahoo.co.jp',
    selector: '#google_ads_iframe_/21827365205',
    updatedAt: '2026-01-03 12:20:05',
    enabled: true,
  },
  {
    id: 'd397b324',
    name: 'Hidden rule',
    note: 'Remove right rail promos.',
    scope: 'page',
    site: 'www.yahoo.co.jp',
    selector: 'div._2KBoKJuH-NgDoy7jHj4A7f',
    updatedAt: '2026-01-03 12:22:49',
    enabled: true,
  },
  {
    id: '039fe1fb',
    name: 'Hidden rule',
    note: 'Remove post card ads.',
    scope: 'page',
    site: '51cg1.com',
    selector: 'div.post-card-ads',
    updatedAt: '2026-01-03 12:30:02',
    enabled: true,
  },
  {
    id: '1806d3b2',
    name: 'Hidden rule',
    note: 'Hide horizontal banner.',
    scope: 'page',
    site: '51cg1.com',
    selector: 'div.horizontal-banner',
    updatedAt: '2026-01-03 12:31:18',
    enabled: true,
  },
  {
    id: 'rule-yahoo-3',
    name: 'Hidden rule',
    note: 'Hide footer widgets.',
    scope: 'page',
    site: 'www.yahoo.co.jp',
    selector: 'div.footer-ads',
    updatedAt: '2026-01-03 12:35:47',
    enabled: true,
  },
  {
    id: 'rule-note-1',
    name: 'Hidden rule',
    note: 'Hide promo banner.',
    scope: 'page',
    site: 'note.com',
    selector: '.promo-banner',
    updatedAt: '2026-01-03 13:01:12',
    enabled: true,
  },
  {
    id: 'rule-note-2',
    name: 'Hidden rule',
    note: 'Remove fixed footer.',
    scope: 'page',
    site: 'note.com',
    selector: 'footer.fixed',
    updatedAt: '2026-01-03 13:05:28',
    enabled: false,
  },
  {
    id: 'rule-mail-1',
    name: 'Hidden rule',
    note: 'Hide chat widget.',
    scope: 'page',
    site: 'mail.google.com',
    selector: 'div[role="dialog"].chat',
    updatedAt: '2026-01-02 12:10:44',
    enabled: true,
  },
  {
    id: 'rule-shop-1',
    name: 'Hidden rule',
    note: 'Suppress cookie banner.',
    scope: 'page',
    site: 'shop.example.com',
    selector: '#cookie-banner',
    updatedAt: '2026-01-01 17:42:31',
    enabled: true,
  },
  {
    id: 'rule-shop-2',
    name: 'Hidden rule',
    note: 'Remove upsell modal.',
    scope: 'page',
    site: 'shop.example.com',
    selector: '.upsell-modal',
    updatedAt: '2026-01-01 17:55:13',
    enabled: true,
  },
  {
    id: 'rule-news-1',
    name: 'Hidden rule',
    note: 'Hide sticky subscribe bar.',
    scope: 'page',
    site: 'news.example.com',
    selector: '.subscribe-bar',
    updatedAt: '2026-01-02 09:20:05',
    enabled: true,
  },
  {
    id: 'rule-news-2',
    name: 'Hidden rule',
    note: 'Hide inline ads.',
    scope: 'page',
    site: 'news.example.com',
    selector: '.inline-ad',
    updatedAt: '2026-01-02 09:26:47',
    enabled: false,
  },
  {
    id: 'rule-pay-1',
    name: 'Hidden rule',
    note: 'Remove trial banner.',
    scope: 'page',
    site: 'pay.openai.com',
    selector: '.trial-banner',
    updatedAt: '2026-01-01 16:42:19',
    enabled: true,
  },
  {
    id: 'rule-pay-2',
    name: 'Hidden rule',
    note: 'Hide helper tooltip.',
    scope: 'page',
    site: 'pay.openai.com',
    selector: '.helper-tooltip',
    updatedAt: '2026-01-01 16:48:37',
    enabled: true,
  },
  {
    id: 'rule-yahoo-4',
    name: 'Hidden rule',
    note: 'Hide sidebar ads.',
    scope: 'page',
    site: 'www.yahoo.co.jp',
    selector: '.sidebar-ad',
    updatedAt: '2026-01-03 12:48:19',
    enabled: true,
  },
  {
    id: 'rule-yahoo-5',
    name: 'Hidden rule',
    note: 'Hide video ads.',
    scope: 'page',
    site: 'www.yahoo.co.jp',
    selector: 'div.video-ads',
    updatedAt: '2026-01-03 12:52:07',
    enabled: false,
  },
];
